# coding: utf-8

"""
    STM Voyage Information Service SeaSWIM API

    Voyage Information Service API facing SeaSWIM through SSC exposing interfaces to SeaSWIM stakeholders

    OpenAPI spec version: 1.0.0
    Contact: per.lofbom@sjofartsverket.se
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_acknowledgement(self):
        """
        Test case for acknowledgement

        
        """
        pass

    def test_get_voyage_plans(self):
        """
        Test case for get_voyage_plans

        
        """
        pass

    def test_remove_voyage_plan_subscription(self):
        """
        Test case for remove_voyage_plan_subscription

        
        """
        pass

    def test_subscribe_to_voyage_plan(self):
        """
        Test case for subscribe_to_voyage_plan

        
        """
        pass

    def test_upload_area(self):
        """
        Test case for upload_area

        
        """
        pass

    def test_upload_text_message(self):
        """
        Test case for upload_text_message

        
        """
        pass

    def test_upload_voyage_plan(self):
        """
        Test case for upload_voyage_plan

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
