# coding: utf-8

"""
    STM Voyage Information Service SeaSWIM API

    Voyage Information Service API facing SeaSWIM through SSC exposing interfaces to SeaSWIM stakeholders

    OpenAPI spec version: 1.0.0
    Contact: per.lofbom@sjofartsverket.se
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest
import requests

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.voyage_plan import VoyagePlan


class TestGetVoyagePlan(unittest.TestCase):
    """ Post VoyagePlan unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetVoyagePlan(self):
        """
        Test VoyagePlan
        """
        CERTPATH='/home/karri/VesselVIS/'
        endPoint='https://ec2-35-157-50-165.eu-central-1.compute.amazonaws.com/voyagePlans'
        payload='{}'
        r=requests.get(endPoint, cert=(CERTPATH + 'Certificate_VIS-Falstaff.pem',CERTPATH + 'PrivateKey_VIS-Falstaff.pem'), verify=CERTPATH + 'mc-ca-chain.pem')
        if r.status_code == 200:
            pass
        print(r.status_code, r.reason)


if __name__ == '__main__':
    unittest.main()
