# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DeliveryAck(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, reference_id: str=None, time_of_delivery: datetime=None, from_id: str=None, from_name: str=None, to_id: str=None, to_name: str=None, ack_result: str=None):
        """
        DeliveryAck - a model defined in Swagger

        :param id: The id of this DeliveryAck.
        :type id: str
        :param reference_id: The reference_id of this DeliveryAck.
        :type reference_id: str
        :param time_of_delivery: The time_of_delivery of this DeliveryAck.
        :type time_of_delivery: datetime
        :param from_id: The from_id of this DeliveryAck.
        :type from_id: str
        :param from_name: The from_name of this DeliveryAck.
        :type from_name: str
        :param to_id: The to_id of this DeliveryAck.
        :type to_id: str
        :param to_name: The to_name of this DeliveryAck.
        :type to_name: str
        :param ack_result: The ack_result of this DeliveryAck.
        :type ack_result: str
        """
        self.swagger_types = {
            'id': str,
            'reference_id': str,
            'time_of_delivery': datetime,
            'from_id': str,
            'from_name': str,
            'to_id': str,
            'to_name': str,
            'ack_result': str
        }

        self.attribute_map = {
            'id': 'id',
            'reference_id': 'referenceId',
            'time_of_delivery': 'timeOfDelivery',
            'from_id': 'fromId',
            'from_name': 'fromName',
            'to_id': 'toId',
            'to_name': 'toName',
            'ack_result': 'ackResult'
        }

        self._id = id
        self._reference_id = reference_id
        self._time_of_delivery = time_of_delivery
        self._from_id = from_id
        self._from_name = from_name
        self._to_id = to_id
        self._to_name = to_name
        self._ack_result = ack_result

    @classmethod
    def from_dict(cls, dikt) -> 'DeliveryAck':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deliveryAck of this DeliveryAck.
        :rtype: DeliveryAck
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this DeliveryAck.
        Id for the ACK

        :return: The id of this DeliveryAck.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this DeliveryAck.
        Id for the ACK

        :param id: The id of this DeliveryAck.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def reference_id(self) -> str:
        """
        Gets the reference_id of this DeliveryAck.
        Reference to delivered message (URN)

        :return: The reference_id of this DeliveryAck.
        :rtype: str
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id: str):
        """
        Sets the reference_id of this DeliveryAck.
        Reference to delivered message (URN)

        :param reference_id: The reference_id of this DeliveryAck.
        :type reference_id: str
        """
        if reference_id is None:
            raise ValueError("Invalid value for `reference_id`, must not be `None`")

        self._reference_id = reference_id

    @property
    def time_of_delivery(self) -> datetime:
        """
        Gets the time_of_delivery of this DeliveryAck.
        Time of delivery

        :return: The time_of_delivery of this DeliveryAck.
        :rtype: datetime
        """
        return self._time_of_delivery

    @time_of_delivery.setter
    def time_of_delivery(self, time_of_delivery: datetime):
        """
        Sets the time_of_delivery of this DeliveryAck.
        Time of delivery

        :param time_of_delivery: The time_of_delivery of this DeliveryAck.
        :type time_of_delivery: datetime
        """
        if time_of_delivery is None:
            raise ValueError("Invalid value for `time_of_delivery`, must not be `None`")

        self._time_of_delivery = time_of_delivery

    @property
    def from_id(self) -> str:
        """
        Gets the from_id of this DeliveryAck.
        Identity of source (sender) of message that have been delivered (URN)

        :return: The from_id of this DeliveryAck.
        :rtype: str
        """
        return self._from_id

    @from_id.setter
    def from_id(self, from_id: str):
        """
        Sets the from_id of this DeliveryAck.
        Identity of source (sender) of message that have been delivered (URN)

        :param from_id: The from_id of this DeliveryAck.
        :type from_id: str
        """
        if from_id is None:
            raise ValueError("Invalid value for `from_id`, must not be `None`")

        self._from_id = from_id

    @property
    def from_name(self) -> str:
        """
        Gets the from_name of this DeliveryAck.
        Friendly name of sender

        :return: The from_name of this DeliveryAck.
        :rtype: str
        """
        return self._from_name

    @from_name.setter
    def from_name(self, from_name: str):
        """
        Sets the from_name of this DeliveryAck.
        Friendly name of sender

        :param from_name: The from_name of this DeliveryAck.
        :type from_name: str
        """
        if from_name is None:
            raise ValueError("Invalid value for `from_name`, must not be `None`")

        self._from_name = from_name

    @property
    def to_id(self) -> str:
        """
        Gets the to_id of this DeliveryAck.
        Identity of target (recipient) of message delivery (URN)

        :return: The to_id of this DeliveryAck.
        :rtype: str
        """
        return self._to_id

    @to_id.setter
    def to_id(self, to_id: str):
        """
        Sets the to_id of this DeliveryAck.
        Identity of target (recipient) of message delivery (URN)

        :param to_id: The to_id of this DeliveryAck.
        :type to_id: str
        """
        if to_id is None:
            raise ValueError("Invalid value for `to_id`, must not be `None`")

        self._to_id = to_id

    @property
    def to_name(self) -> str:
        """
        Gets the to_name of this DeliveryAck.
        Friendly name of recipient

        :return: The to_name of this DeliveryAck.
        :rtype: str
        """
        return self._to_name

    @to_name.setter
    def to_name(self, to_name: str):
        """
        Sets the to_name of this DeliveryAck.
        Friendly name of recipient

        :param to_name: The to_name of this DeliveryAck.
        :type to_name: str
        """
        if to_name is None:
            raise ValueError("Invalid value for `to_name`, must not be `None`")

        self._to_name = to_name

    @property
    def ack_result(self) -> str:
        """
        Gets the ack_result of this DeliveryAck.

        :return: The ack_result of this DeliveryAck.
        :rtype: str
        """
        return self._ack_result

    @ack_result.setter
    def ack_result(self, ack_result: str):
        """
        Sets the ack_result of this DeliveryAck.

        :param ack_result: The ack_result of this DeliveryAck.
        :type ack_result: str
        """
        if ack_result is None:
            raise ValueError("Invalid value for `ack_result`, must not be `None`")

        self._ack_result = ack_result

