# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.voyage_plan import VoyagePlan
from swagger_server.models.base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from swagger_server.util import deserialize_model


class GetVoyagePlanResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, last_interaction_time: datetime=None, voyage_plans: List[VoyagePlan]=None):
        """
        GetVoyagePlanResponse - a model defined in Swagger

        :param last_interaction_time: The last_interaction_time of this GetVoyagePlanResponse.
        :type last_interaction_time: datetime
        :param voyage_plans: The voyage_plans of this GetVoyagePlanResponse.
        :type voyage_plans: List[VoyagePlan]
        """
        self.swagger_types = {
            'last_interaction_time': datetime,
            'voyage_plans': List[VoyagePlan]
        }

        self.attribute_map = {
            'last_interaction_time': 'lastInteractionTime',
            'voyage_plans': 'voyagePlans'
        }

        self._last_interaction_time = last_interaction_time
        self._voyage_plans = voyage_plans

    @classmethod
    def from_dict(cls, dikt) -> 'GetVoyagePlanResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVoyagePlanResponse of this GetVoyagePlanResponse.
        :rtype: GetVoyagePlanResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def last_interaction_time(self) -> datetime:
        """
        Gets the last_interaction_time of this GetVoyagePlanResponse.
        Last interaction time with private application. Can indicate the current connectivity on private side of VIS

        :return: The last_interaction_time of this GetVoyagePlanResponse.
        :rtype: datetime
        """
        return self._last_interaction_time

    @last_interaction_time.setter
    def last_interaction_time(self, last_interaction_time: datetime):
        """
        Sets the last_interaction_time of this GetVoyagePlanResponse.
        Last interaction time with private application. Can indicate the current connectivity on private side of VIS

        :param last_interaction_time: The last_interaction_time of this GetVoyagePlanResponse.
        :type last_interaction_time: datetime
        """

        self._last_interaction_time = last_interaction_time

    @property
    def voyage_plans(self) -> List[VoyagePlan]:
        """
        Gets the voyage_plans of this GetVoyagePlanResponse.
        Array of voyage plans in RTZ XML format

        :return: The voyage_plans of this GetVoyagePlanResponse.
        :rtype: List[VoyagePlan]
        """
        return self._voyage_plans

    @voyage_plans.setter
    def voyage_plans(self, voyage_plans: List[VoyagePlan]):
        """
        Sets the voyage_plans of this GetVoyagePlanResponse.
        Array of voyage plans in RTZ XML format

        :param voyage_plans: The voyage_plans of this GetVoyagePlanResponse.
        :type voyage_plans: List[VoyagePlan]
        """

        self._voyage_plans = voyage_plans

