# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ResponseObj(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, body: str=None):
        """
        ResponseObj - a model defined in Swagger

        :param body: The body of this ResponseObj.
        :type body: str
        """
        self.swagger_types = {
            'body': str
        }

        self.attribute_map = {
            'body': 'body'
        }

        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseObj':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The responseObj of this ResponseObj.
        :rtype: ResponseObj
        """
        return deserialize_model(dikt, cls)

    @property
    def body(self) -> str:
        """
        Gets the body of this ResponseObj.

        :return: The body of this ResponseObj.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """
        Sets the body of this ResponseObj.

        :param body: The body of this ResponseObj.
        :type body: str
        """
        if body is None:
            raise ValueError("Invalid value for `body`, must not be `None`")

        self._body = body

