# coding: utf-8

"""
    STM Voyage Information Service SeaSWIM API

    Voyage Information Service API facing SeaSWIM through SSC exposing interfaces to SeaSWIM stakeholders

    OpenAPI spec version: 1.0.0
    Contact: per.lofbom@sjofartsverket.se
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.delivery_ack import DeliveryAck
from .models.error_model import ErrorModel
from .models.get_vp_response_object import GetVPResponseObject
from .models.response_obj import ResponseObj
from .models.s124_data_set import S124DataSet
from .models.text_message_object import TextMessageObject
from .models.voyage_plan import VoyagePlan

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
