---
swagger: "2.0"
info:
  description: "Changes in 1.1.0 is; Update of descriptions; GetVoyagePlanResponse;\
    \ VoyagePlan"
  version: "1.1.0"
  title: "STM Voyage Information Service SeaSWIM API"
host: "localhost"
basePath: "/"
schemes:
- "http"
- "https"
paths:
  /acknowledgement:
    post:
      tags:
      - "Acknowledgement"
      summary: ""
      description: "Endpoint for receipt of acknowledgement of uploaded message"
      operationId: "acknowledgement"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "deliveryAck"
        description: "Acknowledgement"
        required: true
        schema:
          $ref: "#/definitions/DeliveryAck"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be authenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.acknowledgement_controller"
  /area:
    post:
      tags:
      - "Area"
      summary: ""
      description: "Upload area message to VIS from other services i.e. Route Check\
        \ service as an informational message"
      operationId: "upload_area"
      consumes:
      - "text/xml"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "area"
        description: "Uploaded area message in S124 format to consumer"
        required: true
        schema:
          type: "string"
      - name: "deliveryAckEndPoint"
        in: "query"
        description: "Acknowledgement expected. Base URL for VIS as in Service Registry.\
          \ An ack is send back to this url when the private application retrieve\
          \ the message from the VIS "
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be auhtenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.area_controller"
  /textMessage:
    post:
      tags:
      - "TextMessage"
      summary: ""
      description: "Upload text message to VIS from other services i.e. Route Optimization\
        \ service."
      operationId: "upload_text_message"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "textMessageObject"
        description: "Uploaded Text message to consumer"
        required: true
        schema:
          type: "string"
      - name: "deliveryAckEndPoint"
        in: "query"
        description: "Acknowledgement expected. Base URL for VIS as in Service Registry.\
          \ An ack is send back to this url when the private application retrieve\
          \ the message from the VIS "
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be auhtenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.text_message_controller"
  /voyagePlans:
    get:
      tags:
      - "VoyagePlan"
      summary: ""
      description: "Returns active VoyagePlans"
      operationId: "get_voyage_plans"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "uvid"
        in: "query"
        description: "Unique identity (URN) of a voyageplan"
        required: false
        type: "string"
      - name: "routeStatus"
        in: "query"
        description: "Status of a route for a voyageplan: 1-Original   2-Planned_for_voyage\
          \    3-Optimized 4-Cross_Checked 5-Safety_Checked    6-Approved  7-Used_for_monitoring\
          \   8-Inactive"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/GetVoyagePlanResponse"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be auhtenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden (Not authorized request forwarded to operator)"
        404:
          description: "Not Found (the requested voyagePlan is not found)"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.voyage_plan_controller"
    post:
      tags:
      - "VoyagePlan"
      summary: ""
      description: "Upload VoyagePlan to VIS from other services i.e. Route Optimization\
        \ service."
      operationId: "upload_voyage_plan"
      consumes:
      - "text/xml"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "voyagePlan"
        description: "Voyage Plan in RTZ format"
        required: true
        schema:
          type: "string"
      - name: "deliveryAckEndPoint"
        in: "query"
        description: "Acknowledgement expected. Base URL for VIS as in Service Registry.\
          \ An ack is send back to this url when the private application retrieve\
          \ the message from the VIS "
        required: false
        type: "string"
      - name: "callbackEndpoint"
        in: "query"
        description: "Callback expected. Base url of the vis instance as in the Service\
          \ Registry. The callback response will be sended to the voyagePlans endPoint\
          \ of the instance"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be auhtenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.voyage_plan_controller"
  /voyagePlans/subscription:
    get:
      tags:
      - "VoyagePlan"
      summary: ""
      description: "Retrieve a list of subcribed UVID for the callBackEndPoint and\
        \ Organization"
      operationId: "get_subscription_to_voyage_plans"
      consumes: []
      produces:
      - "application/json"
      parameters:
      - name: "callbackEndpoint"
        in: "query"
        description: "Callback expected. Base url of the vis instance as in the Service\
          \ Registry. The callback response will be sended to the voyagePlans endPoint\
          \ of the instance"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GetSubscriptionResponse"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be authenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden (Not authorized request forwarded to operator)"
        404:
          description: "Not Found (the requested Voyage Plan is not found)"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.voyage_plan_controller"
    post:
      tags:
      - "VoyagePlan"
      summary: ""
      description: "Request subscription for active Voyage Plan from other services\
        \ i.e. Enhanced Monitoring"
      operationId: "subscribe_to_voyage_plan"
      consumes: []
      produces:
      - "application/json"
      parameters:
      - name: "callbackEndpoint"
        in: "query"
        description: "Callback expected. Base url of the vis instance as in the Service\
          \ Registry. The callback response will be sended to the voyagePlans endPoint\
          \ of the instance"
        required: true
        type: "string"
      - name: "uvid"
        in: "query"
        description: "Unique identity (URN) of a voyageplan. If no uvid is provided,\
          \ the subcription is to all the active uvid that your organization has access\
          \ to"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be auhtenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden (Not authorized request forwarded to operator)"
        404:
          description: "Not Found (the requested Voyage Plan is not found)"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.voyage_plan_controller"
    delete:
      tags:
      - "VoyagePlan"
      summary: ""
      description: "Remove subscription for active Voyage Plan from other services\
        \ i.e. Enhanced Monitoring"
      operationId: "remove_voyage_plan_subscription"
      consumes: []
      produces:
      - "application/json"
      parameters:
      - name: "callbackEndpoint"
        in: "query"
        description: "Callback expected. Base url of the vis instance as in the Service\
          \ Registry. The callback response will be sended to the voyagePlans endPoint\
          \ of the instance"
        required: true
        type: "string"
      - name: "uvid"
        in: "query"
        description: "Unique identity (URN) of a voyageplan"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized (the user cannot be auhtenticated in the Identity\
            \ Registry)"
        403:
          description: "Forbidden"
        404:
          description: "Not Found (the requested Voyage Plan is not found)"
        500:
          description: "Internal Server Error"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.voyage_plan_controller"
definitions:
  DeliveryAck:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Acknowledgement ID"
      referenceId:
        type: "string"
        description: "Reference ID such as a UVID, TXT id or area message id"
      timeOfDelivery:
        type: "string"
        format: "date-time"
        description: "Time of Delivery of message to consumer"
      fromId:
        type: "string"
        description: "Identity O (organisation) of the message sender in MRN format"
      fromName:
        type: "string"
        description: "\"Identity O (organisation) of the message sender in full name"
      toId:
        type: "string"
        description: "Identity O (organisation) of the message receiver in MRN format"
      toName:
        type: "string"
        description: "IIdentity O (organisation) of the message receiver in full name"
      ackResult:
        type: "string"
        description: "Descriptive acknowledgement message"
    description: "Acknowledgement message that incoming (uploaded) message has been\
      \ delivered to consumer"
  GetVoyagePlanResponse:
    type: "object"
    properties:
      lastInteractionTime:
        type: "string"
        format: "date-time"
        description: "Last interaction time with private application. Can indicate\
          \ the current connectivity on private side of VIS"
      voyagePlans:
        type: "array"
        description: "Array of voyage plans in RTZ XML format"
        items:
          $ref: "#/definitions/VoyagePlan"
    description: "Response object from GET voyagePlans. Can contain 0 or several (0..*)\
      \ voyage plans"
  VoyagePlan:
    type: "object"
    properties:
      route:
        type: "string"
        description: "A voyage plan in RTZ XML format"
    description: "A voyage plan in RTZ XML format"
  GetSubscriptionResponse:
    type: "object"
    properties:
      DataId:
        type: "string"
        description: "Unique identity (URN) of a voyageplan"
    description: "DataId object containing the UVID in URN format"
